version: '3'

services:
  syncer:
    init: true
    container_name: discord_bot
    hostname: discord_bot
    build: .
    environment:
      - DC_BOT_TOKEN=${DC_BOT_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - CHANNEL_IDS=${CHANNEL_IDS}
      - GH_TOKEN=${GH_TOKEN}
      - GH_ORG=${GH_ORG}
      - GH_REPO=${GH_REPO}
      - GH_PROJECT_NUMBER=${GH_PROJECT_NUMBER}
    restart: on-failure
    networks:
      botnet:
        ipv4_address: 10.10.13.3

networks:
  botnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.13.0/24
          gateway: 10.10.13.1
