version: '3'

services:
  syncer:
    container_name: discord_bot
    hostname: discord_bot
    build: .
    command: node dist/index.js
    environment:
      - NODE_ENV=production
      - CHANNEL_IDS=${CHANNEL_IDS}
      - GUILD_ID=${GUILD_ID}
      - DC_BOT_TOKEN=${DC_BOT_TOKEN}
      - DC_EMBED_COLOR=${DC_EMBED_COLOR}
      - DC_ERROR_COLOR=${DC_ERROR_COLOR}
      - DC_SUCCESS_COLOR=${DC_SUCCESS_COLOR}
      - GH_ORG=${GH_ORG}
      - GH_REPO=${GH_REPO}
      - GH_PROJECT_NUMBER=${GH_PROJECT_NUMBER}
      - GH_TOKEN=${GH_TOKEN}
    restart: on-failure
    networks:
      botnet:
        ipv4_address: 10.10.13.3

networks:
  botnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.13.0/24
          gateway: 10.10.13.1
